name: Clone and commit workflow

on:
  push:
    branches:
      - main 
jobs:
  clone_and_commit:
    runs-on: ubuntu-latest
    permissions:
      actions: write 
    steps:
      
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo " The ${{ github.repository }} repository has been cloned to the runner."


      - name: Create ZIP archive
        run: |
          zip -r my_files.zip .
      
      - name: Clone work2 repository
        run: git clone https://github.com/ptmnational/work2.git

      
          

     
      - name: Git Configure  
        run: |
          cd work2
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Commit changes  
        run: |
          cd work2
          
          git add ./my_files.zip
          git commit -m "Commit from github action"
          
      - name: Push changes to work2
        run: |
          cd work1
          git push https://x-access-token:${{ secrets.WORKFL_TOK }}@github.com/ptmnational/work2.git HEAD:refs/heads/main
          
