name: Clone and commit workflow

on:
  push:
    branches:
      - main 
jobs:
  clone_and_commit:
    runs-on: ubuntu-latest
    permissions:
      actions: write 
    steps:
      
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo " The ${{ github.repository }} repository has been cloned to the runner."
      
      - name: Clone work2 repository
        run: |
          git clone https://github.com/ptmnational/work2.git
          git add.
      - name: Commit changes  
        run: |
          cd work2
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Commit from github action"
          
      - name: Push changes to work2
        run: |
          cd work2
          git push https://github.com/ptmnational/work2.git HEAD:refs/heads/main
