name: Workflow1

on:
  push:
    branches:
      - main

jobs:
  create-zip-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create ZIP archive
        run: |
          zip -r my_files.zip .
        
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Add, commit, and push ZIP file
        run: |
          git add my_files.zip
          git commit -m "Add my_files.zip"
          git push origin main
