name: Workflow1

on:
  push:
    branches:
      - main

jobs:
  create-zip-and-send:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create ZIP archive
        run: |
          zip -r my_files.zip .
        
      - name: Push changes to work2
        run: |
         
          git push https://x-access-token:${{ secrets.WORKFL_TOK }}@github.com/ptmnational/work2.git HEAD:refs/heads/main
          
