name: Workflow1.1

on:
  push:
    branches:
      - main

jobs:
  create-zip-and-store:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Create ZIP archive
        run: |
          zip -r my_files.zip .
        
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Add ZIP file as a new branch
        run: |
          mv my_files.zip temp_branch/
          git add temp_branch/my_files.zip
          git commit -m "Add my_files.zip"
          git push origin temp_branch
